In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np


import os

In [43]:
#Programme d'aggrégation des fichiers meteo synop mensuel téléchargés à partir du site de météo-france

# remarques anciens fichiers synop à l'adresse https://www.data.gouv.fr/datasets/archive-synop-omm

In [3]:
#Répertoire des données brutes
rep="/home/dominique/DATA/meteo/données_climat/"

#Suffixe des fichiers des données brutes
suff1=".csv"
suff2=".json"

In [4]:
#Liste des fichiers de rep

contenu_rep=os.listdir(rep)

In [5]:
#Liste des fichiers par type
liste_csv=[]
liste_json=[]
liste_autre=[]

#Formation des listes
for fich in contenu_rep:
    suffixe=fich[-4:]   #formulation plus générale à trouver : couper au point 
    if suffixe==suff1:
        liste_csv.append(fich)
    elif suffixe=="json":
        liste_json.append(fich)
    else:
        liste_autre.append(fich)

#Effectif des listes
nb_csv=len(liste_csv)
nb_json=len(liste_json)
nb_autre=len(liste_autre)

#Affichage
print(f"Nous avons {nb_csv} fichiers de type csv , {nb_json} de type json et {nb_autre} d'autres types.")

Nous avons 360 fichiers de type csv , 1 de type json et 0 d'autres types.

In [6]:
#Exploration liste csv
liste_csv

['climat.200910.csv',
 'climat.200610.csv',
 'climat.202411.csv',
 'climat.200001.csv',
 'climat.200911.csv',
 'climat.199807.csv',
 'climat.202102.csv',
 'climat.201708.csv',
 'climat.202405.csv',
 'climat.201012.csv',
 'climat.202002.csv',
 'climat.201808.csv',
 'climat.200810.csv',
 'climat.201508.csv',
 'climat.199709.csv',
 'climat.199701.csv',
 'climat.200208.csv',
 'climat.202107.csv',
 'climat.199810.csv',
 'climat.200908.csv',
 'climat.201408.csv',
 'climat.202304.csv',
 'climat.199802.csv',
 'climat.200807.csv',
 'climat.201301.csv',
 'climat.200805.csv',
 'climat.199712.csv',
 'climat.201601.csv',
 'climat.201512.csv',
 'climat.200406.csv',
 'climat.202109.csv',
 'climat.201310.csv',
 'climat.200111.csv',
 'climat.199908.csv',
 'climat.202505.csv',
 'climat.199710.csv',
 'climat.201510.csv',
 'climat.201609.csv',
 'climat.200608.csv',
 'climat.199703.csv',
 'climat.202104.csv',
 'climat.201701.csv',
 'climat.202308.csv',
 'climat.201404.csv',
 'climat.199607.csv',
 'climat.201307.csv',
 'climat.201905.csv',
 'climat.201906.csv',
 'climat.201104.csv',
 'climat.201308.csv',
 'climat.202509.csv',
 'climat.200901.csv',
 'climat.201403.csv',
 'climat.202106.csv',
 'climat.200506.csv',
 'climat.202503.csv',
 'climat.202307.csv',
 'climat.201106.csv',
 'climat.200511.csv',
 'climat.200212.csv',
 'climat.199601.csv',
 'climat.201805.csv',
 'climat.201612.csv',
 'climat.201305.csv',
 'climat.200004.csv',
 'climat.200401.csv',
 'climat.200701.csv',
 'climat.200407.csv',
 'climat.201611.csv',
 'climat.202306.csv',
 'climat.200710.csv',
 'climat.202110.csv',
 'climat.200211.csv',
 'climat.200009.csv',
 'climat.200306.csv',
 'climat.200309.csv',
 'climat.200505.csv',
 'climat.202401.csv',
 'climat.200310.csv',
 'climat.201810.csv',
 'climat.202512.csv',
 'climat.201606.csv',
 'climat.201109.csv',
 'climat.201208.csv',
 'climat.201207.csv',
 'climat.201712.csv',
 'climat.200705.csv',
 'climat.201910.csv',
 'climat.201507.csv',
 'climat.200902.csv',
 'climat.201506.csv',
 'climat.200102.csv',
 'climat.200109.csv',
 'climat.200801.csv',
 'climat.200512.csv',
 'climat.199906.csv',
 'climat.201704.csv',
 'climat.202508.csv',
 'climat.202003.csv',
 'climat.201406.csv',
 'climat.202406.csv',
 'climat.202312.csv',
 'climat.200103.csv',
 'climat.202210.csv',
 'climat.201011.csv',
 'climat.200507.csv',
 'climat.200209.csv',
 'climat.201103.csv',
 'climat.200012.csv',
 'climat.200909.csv',
 'climat.200809.csv',
 'climat.201105.csv',
 'climat.199608.csv',
 'climat.201311.csv',
 'climat.202502.csv',
 'climat.201503.csv',
 'climat.199706.csv',
 'climat.200601.csv',
 'climat.200204.csv',
 'climat.201007.csv',
 'climat.200412.csv',
 'climat.200510.csv',
 'climat.200604.csv',
 'climat.201212.csv',
 'climat.201903.csv',
 'climat.199609.csv',
 'climat.199611.csv',
 'climat.200606.csv',
 'climat.200502.csv',
 'climat.201608.csv',
 'climat.200307.csv',
 'climat.200607.csv',
 'climat.201909.csv',
 'climat.202105.csv',
 'climat.200602.csv',
 'climat.200106.csv',
 'climat.202209.csv',
 'climat.201502.csv',
 'climat.199604.csv',
 'climat.200311.csv',
 'climat.199901.csv',
 'climat.200409.csv',
 'climat.201804.csv',
 'climat.201509.csv',
 'climat.200712.csv',
 'climat.200101.csv',
 'climat.201702.csv',
 'climat.199909.csv',
 'climat.200206.csv',
 'climat.200312.csv',
 'climat.199606.csv',
 'climat.201904.csv',
 'climat.199704.csv',
 'climat.201809.csv',
 'climat.201107.csv',
 'climat.202103.csv',
 'climat.202506.csv',
 'climat.201811.csv',
 'climat.200402.csv',
 'climat.201006.csv',
 'climat.200611.csv',
 'climat.202012.csv',
 'climat.202510.csv',
 'climat.202507.csv',
 'climat.200905.csv',
 'climat.201812.csv',
 'climat.200912.csv',
 'climat.201807.csv',
 'climat.201705.csv',
 'climat.200405.csv',
 'climat.201706.csv',
 'climat.199903.csv',
 'climat.201407.csv',
 'climat.200804.csv',
 'climat.200302.csv',
 'climat.199907.csv',
 'climat.201401.csv',
 'climat.200907.csv',
 'climat.200404.csv',
 'climat.200501.csv',
 'climat.202302.csv',
 'climat.201102.csv',
 'climat.202007.csv',
 'climat.201505.csv',
 'climat.201210.csv',
 'climat.200205.csv',
 'climat.199910.csv',
 'climat.202004.csv',
 'climat.200301.csv',
 'climat.202403.csv',
 'climat.200806.csv',
 'climat.200411.csv',
 'climat.202408.csv',
 'climat.200408.csv',
 'climat.201911.csv',
 'climat.200008.csv',
 'climat.200006.csv',
 'climat.199806.csv',
 'climat.200509.csv',
 'climat.201002.csv',
 'climat.201108.csv',
 'climat.202310.csv',
 'climat.201309.csv',
 'climat.201912.csv',
 'climat.201901.csv',
 'climat.200308.csv',
 'climat.200703.csv',
 'climat.202201.csv',
 'climat.200203.csv',
 'climat.202404.csv',
 'climat.201206.csv',
 'climat.201010.csv',
 'climat.202206.csv',
 'climat.199902.csv',
 'climat.199612.csv',
 'climat.201410.csv',
 'climat.200812.csv',
 'climat.202203.csv',
 'climat.201209.csv',
 'climat.200906.csv',
 'climat.200704.csv',
 'climat.199911.csv',
 'climat.200603.csv',
 'climat.201511.csv',
 'climat.202208.csv',
 'climat.201008.csv',
 'climat.199803.csv',
 'climat.201908.csv',
 'climat.201302.csv',
 'climat.200811.csv',
 'climat.201402.csv',
 'climat.200201.csv',
 'climat.200210.csv',
 'climat.201201.csv',
 'climat.201710.csv',
 'climat.201411.csv',
 'climat.200303.csv',
 'climat.201902.csv',
 'climat.199610.csv',
 'climat.200808.csv',
 'climat.201409.csv',
 'climat.200410.csv',
 'climat.199801.csv',
 'climat.200711.csv',
 'climat.202009.csv',
 'climat.201604.csv',
 'climat.202211.csv',
 'climat.200112.csv',
 'climat.200904.csv',
 'climat.202402.csv',
 'climat.200702.csv',
 'climat.202412.csv',
 'climat.201101.csv',
 'climat.200202.csv',
 'climat.199602.csv',
 'climat.200003.csv',
 'climat.200504.csv',
 'climat.200609.csv',
 'climat.200708.csv',
 'climat.201001.csv',
 'climat.199708.csv',
 'climat.200709.csv',
 'climat.201205.csv',
 'climat.200007.csv',
 'climat.202501.csv',
 'climat.199804.csv',
 'climat.201412.csv',
 'climat.199905.csv',
 'climat.201204.csv',
 'climat.199912.csv',
 'climat.200304.csv',
 'climat.202112.csv',
 'climat.201703.csv',
 'climat.200305.csv',
 'climat.202303.csv',
 'climat.199702.csv',
 'climat.200002.csv',
 'climat.201607.csv',
 'climat.201610.csv',
 'climat.201009.csv',
 'climat.201602.csv',
 'climat.202311.csv',
 'climat.202005.csv',
 'climat.200108.csv',
 'climat.200005.csv',
 'climat.202204.csv',
 'climat.199603.csv',
 'climat.201802.csv',
 'climat.201211.csv',
 'climat.202010.csv',
 'climat.200110.csv',
 'climat.201111.csv',
 'climat.201003.csv',
 'climat.201806.csv',
 'climat.202301.csv',
 'climat.201605.csv',
 'climat.199808.csv',
 'climat.201304.csv',
 'climat.202205.csv',
 'climat.202212.csv',
 'climat.199605.csv',
 'climat.202309.csv',
 'climat.202111.csv',
 'climat.202305.csv',
 'climat.202504.csv',
 'climat.202207.csv',
 'climat.201004.csv',
 'climat.200105.csv',
 'climat.201907.csv',
 'climat.201504.csv',
 'climat.201202.csv',
 'climat.202407.csv',
 'climat.199707.csv',
 'climat.201303.csv',
 'climat.200612.csv',
 'climat.202108.csv',
 'climat.200508.csv',
 'climat.200802.csv',
 'climat.200403.csv',
 'climat.199705.csv',
 'climat.201803.csv',
 'climat.200104.csv',
 'climat.201112.csv',
 'climat.202006.csv',
 'climat.200605.csv',
 'climat.201405.csv',
 'climat.202001.csv',
 'climat.199812.csv',
 'climat.201711.csv',
 'climat.201801.csv',
 'climat.202410.csv',
 'climat.200107.csv',
 'climat.201707.csv',
 'climat.201110.csv',
 'climat.199809.csv',
 'climat.202202.csv',
 'climat.199805.csv',
 'climat.199904.csv',
 'climat.201312.csv',
 'climat.200903.csv',
 'climat.201603.csv',
 'climat.199811.csv',
 'climat.200803.csv',
 'climat.200207.csv',
 'climat.202511.csv',
 'climat.202101.csv',
 'climat.201005.csv',
 'climat.200707.csv',
 'climat.200503.csv',
 'climat.199711.csv',
 'climat.201203.csv',
 'climat.200706.csv',
 'climat.201306.csv',
 'climat.201501.csv',
 'climat.201709.csv',
 'climat.200011.csv',
 'climat.202011.csv',
 'climat.202409.csv',
 'climat.202008.csv',
 'climat.200010.csv']

In [7]:
#Lecture et concatenation des fichiers mois --> toutes variables

In [8]:
#intialisation avec premier fichier de la liste
df=pd.read_csv(rep+liste_csv[0],sep=";")

#incrementation
for i,fichier in enumerate(liste_csv):
    if i>0:
        df_fich=pd.read_csv(rep+fichier,sep=";")
        df=pd.concat([df_fich,df],axis=0)
#Réindexation
df=df.reset_index(drop=True)
#Dimension du fichier 
nb_lign=df.shape[0]
nb_col=df.shape[1]

print(f"Le fichier complet comporte {nb_lign} lignes et {nb_col} colonnes.")

Le fichier complet comporte 19355 lignes et 54 colonnes.

In [9]:
df.dtypes

NUM_POSTE        int64
DAT             object
PSTATM         float64
PMERM          float64
TMMOY          float64
TMSIGMA        float64
TXMOY          float64
TNMOY          float64
TSVMOY         float64
RR             float64
NBJRR1         float64
INST           float64
NBPMER         float64
NBTM           float64
NBTX           float64
NBTSV          float64
NBRR           float64
NBINS          float64
NBJTX25        float64
NBJTX30        float64
NBJTX35        float64
NBJTX40        float64
NBJTX0         float64
NBJTN0         float64
NBJRR5         float64
NBJRR10        float64
NBJRR50        float64
NBJRR100       float64
NBJNEIG0       float64
NBJNEIG1       float64
NBJNEIG10      float64
NBJNEIG50      float64
NBJFF10        float64
NBJFF20        float64
NBJFF30        float64
NBJVISI50      float64
NBJVISI100     float64
NBJVISI1000    float64
TMXAB          float64
TMXDAT          object
TMNAB          float64
TMNDAT          object
TXAB           float64
TXDAT           object
TNAB           float64
TNDAT           object
RRAB           float64
RRDAT           object
FXAB           float64
FXDAT           object
NBORAGE        float64
NBGRELE        float64
HTX            float64
HTN            float64
dtype: object

In [10]:
liste_variables=list(df.columns)

In [11]:
#Analyse des données manquantes et % manquant par ligne et colonne

In [12]:
##Création d'un dataframe miroir codé en binaire : 0 donnée présente - 1 donnée absente
#Copie du df
df_mq=df
#transformation, remplacement des colonnes sauf la première colonne qui donne les n° de postes (=stations)
for i,var in enumerate(liste_variables[1:]):
    nom=var+"_mq"
    df_mq[nom]=df_mq[var].apply(lambda x:1 if pd.isna(x) else 0)
    df_mq=df_mq.drop([var],axis=1)

In [13]:
#Calcul des sommes par colonnes 
df_mq_col=pd.DataFrame(liste_variables,columns=["Variable"])
df_mq_col["Total"]=list(df_mq.sum())

df_mq_col=df_mq_col.drop(0)
df_mq_col=df_mq_col.reset_index(drop=True)   

df_mq_col["Taux%"]=df_mq_col["Total"]*100/nb_lign
df_mq_col["Taux%"]=df_mq_col["Taux%"].apply(lambda x:np.round(x,1))

In [14]:
df_mq_col.sort_values(by="Taux%",ascending=False)

       Variable  Total  Taux%
30    NBJNEIG50  19046   98.4
29    NBJNEIG10  19046   98.4
26     NBJRR100  18597   96.1
27     NBJNEIG0  17962   92.8
28     NBJNEIG1  17962   92.8
19      NBJTX35  17501   90.4
20      NBJTX40  17500   90.4
21       NBJTX0  13086   67.6
22       NBJTN0  13090   67.6
34    NBJVISI50  10711   55.3
50      NBGRELE  10057   52.0
35   NBJVISI100   9870   51.0
17      NBJTX25   9562   49.4
18      NBJTX30   9415   48.6
36  NBJVISI1000   7487   38.7
49      NBORAGE   6453   33.3
24      NBJRR10   5288   27.3
25      NBJRR50   5262   27.2
10         INST   4845   25.0
23       NBJRR5   1492    7.7
2         PMERM   1344    6.9
45         RRAB   1059    5.5
47         FXAB   1062    5.5
46        RRDAT    975    5.0
48        FXDAT    855    4.4
1        PSTATM    861    4.4
32      NBJFF20    818    4.2
33      NBJFF30    818    4.2
31      NBJFF10    819    4.2
8            RR    809    4.2
9        NBJRR1    809    4.2
43         TNAB    725    3.7
44        TNDAT    721    3.7
42        TXDAT    718    3.7
37        TMXAB    528    2.7
38       TMXDAT    523    2.7
39        TMNAB    475    2.5
41         TXAB    459    2.4
40       TMNDAT    470    2.4
15         NBRR    302    1.6
51          HTX    286    1.5
52          HTN    285    1.5
7        TSVMOY    258    1.3
16        NBINS    224    1.2
12         NBTM    211    1.1
14        NBTSV    221    1.1
11       NBPMER    211    1.1
13         NBTX    211    1.1
4       TMSIGMA    189    1.0
5         TXMOY    191    1.0
6         TNMOY    192    1.0
3         TMMOY    179    0.9
0           DAT      0    0.0

In [15]:
#Calcul des sommes par lignes
df_mq_1=df[["NUM_POSTE","DAT"]]
df_mq_2=df_mq.drop(["NUM_POSTE","DAT_mq"],axis=1)

#Réindexation
df_mq_1=df_mq_1.reset_index(drop=True)
df_mq_2=df_mq_2.reset_index(drop=True)

#On commence le total à la colonne 2  de df_mq_2
df_mq_2["Total"]=df_mq_2.sum(axis=1)
df_mq_2=df_mq_2[["Total"]]

#On concatène les 2
df_mq_lign=pd.concat([df_mq_1,df_mq_2],axis=1)
df_mq_lign["Taux%"]=df_mq_lign["Total"]/(nb_col-2)*100
df_mq_lign["Taux%"]=df_mq_lign["Taux%"].apply(lambda x:np.round(x,1))

In [16]:
df_mq_lign

       NUM_POSTE                  DAT  Total  Taux%
0           7005  2000-10-01 00:00:00     11   21.2
1           7015  2000-10-01 00:00:00     13   25.0
2           7020  2000-10-01 00:00:00     15   28.8
3           7027  2000-10-01 00:00:00     13   25.0
4           7037  2000-10-01 00:00:00     11   21.2
...          ...                  ...    ...    ...
19350      81401  2009-10-01 00:00:00     20   38.5
19351      81405  2009-10-01 00:00:00      9   17.3
19352      81408  2009-10-01 00:00:00     13   25.0
19353      81415  2009-10-01 00:00:00     13   25.0
19354      89642  2009-10-01 00:00:00     20   38.5

[19355 rows x 4 columns]

In [17]:
df_mq_lign["Taux%"].max()

96.2

In [18]:
#FIN CONCATENATION des fichiers

In [19]:
liste_index=df.index

In [20]:
#analyse de la variable NBJTX30
df2=df.loc[liste_index,["NUM_POSTE","DAT","NBJTX30","TXAB"]]

In [21]:
df2["mq"]=df2["NBJTX30"].apply(lambda x : 1 if pd.isna(x) else 0)

In [22]:
an=[]
mois=[]
for i,date in enumerate(list(df2["DAT"])):
    an_date=date[0:4]
    mois_date=date[5:7]
    an.append(an_date)
    mois.append(mois_date)

df2["an"]=an
df2["mois"]=mois

In [23]:
#REDUCTION du NOMBRE de MANQUANTS de NBJTX30

##On ajoute une variable de test : est ce que la température max du mois est >=30
##Si la réponse est non (=0=, alors nécessairement NBJTX30 doit être nul pour le mois correspondant 
##Dans ce cas si NBJTX30 est manquant , on le remplace par 0
df2["TX>=30"]=df2["TXAB"].apply(lambda x:1 if x>=30 else 0)

##Boucle de correction
##Correction : NBJTTX30 passe à 0 lorsque TX>=30 = 0 avec TXAB non manquant

for i in range(df2.shape[0]):
    test1=df2.loc[i,"mq"]
    test2=df2.loc[i,"TXAB"]
    
    if (test1==1)  & (not pd.isna(test2)):
        #test sur TX>=30
        test3=df2.loc[i,"TX>=30"]
        #Corrections si TXW>=30 est à 0
        if test3==0:
            df2.loc[i,"TXAB"]=0
            df2.loc[i,"mq"]=0
            df2.loc[i,"NBJTX30"]=0

In [24]:
df2

       NUM_POSTE                  DAT  NBJTX30  TXAB  mq    an mois  TX>=30
0           7005  2000-10-01 00:00:00      0.0   0.0   0  2000   10       0
1           7015  2000-10-01 00:00:00      0.0   0.0   0  2000   10       0
2           7020  2000-10-01 00:00:00      0.0   0.0   0  2000   10       0
3           7027  2000-10-01 00:00:00      0.0   0.0   0  2000   10       0
4           7037  2000-10-01 00:00:00      0.0   0.0   0  2000   10       0
...          ...                  ...      ...   ...  ..   ...  ...     ...
19350      81401  2009-10-01 00:00:00      NaN  35.8   1  2009   10       1
19351      81405  2009-10-01 00:00:00     31.0  34.3   0  2009   10       1
19352      81408  2009-10-01 00:00:00     31.0  36.0   0  2009   10       1
19353      81415  2009-10-01 00:00:00     31.0  36.7   0  2009   10       1
19354      89642  2009-10-01 00:00:00      0.0   0.0   0  2009   10       0

[19355 rows x 8 columns]

In [26]:
#Le taux total est très correct
#On analyse la répartition des manquants par poste , année et mois sur la version corrigée de df2

In [27]:
#Premier point : y-a-t-il des stations plus touchées que d'autres

df2_poste=df2.groupby(by=["NUM_POSTE"],as_index=False).agg({"mq":"sum","TXAB":"count"})
df2_poste=df2_poste.rename({"TXAB":"nombre"},axis=1)
df2_poste["taux%"]=df2_poste["mq"]*100/df2_poste["nombre"]
df2_poste=df2_poste.sort_values(by=["taux%"],ascending=False)

In [28]:
df2_poste

    NUM_POSTE  mq  nombre      taux%
37       7661  70     290  24.137931
56      81415  55     282  19.503546
43      61970  42     222  18.918919
52      78925  49     281  17.437722
48      61997  36     229  15.720524
42      61968  36     230  15.652174
45      61976  29     263  11.026616
53      81401  25     248  10.080645
46      61980  20     277   7.220217
44      61972  17     249   6.827309
50      67005  15     270   5.555556
47      61996  13     244   5.327869
55      81408  16     310   5.161290
54      81405  14     339   4.129794
49      61998   7     263   2.661597
13       7190   5     353   1.416431
51      78897   4     295   1.355932
57      89642   2     265   0.754717
6        7110   1     359   0.278552
18       7280   1     359   0.278552
22       7434   1     359   0.278552
20       7314   1     359   0.278552
14       7207   1     359   0.278552
15       7222   1     359   0.278552
17       7255   1     359   0.278552
3        7027   1     359   0.278552
2        7020   1     359   0.278552
26       7510   1     359   0.278552
23       7460   0     360   0.000000
21       7335   0     360   0.000000
19       7299   0     360   0.000000
11       7168   0     280   0.000000
10       7149   0     360   0.000000
16       7240   0     360   0.000000
12       7181   0     280   0.000000
0        7005   0     359   0.000000
1        7015   0     359   0.000000
4        7037   0     360   0.000000
5        7072   0     161   0.000000
7        7117   0     345   0.000000
8        7130   0     346   0.000000
9        7139   0     346   0.000000
25       7481   0     360   0.000000
24       7471   0     360   0.000000
41       7790   0     360   0.000000
40       7761   0     360   0.000000
36       7650   0     360   0.000000
35       7643   0     360   0.000000
39       7747   0     360   0.000000
38       7690   0     360   0.000000
29       7577   0     360   0.000000
32       7621   0     360   0.000000
31       7607   0     360   0.000000
30       7591   0     360   0.000000
27       7535   0     360   0.000000
28       7560   0     360   0.000000
34       7630   0     360   0.000000
33       7627   0     360   0.000000

In [29]:
df2_an=df2.groupby(by=["an"],as_index=False).agg({"mq":"sum","TXAB":"count"})
df2_an=df2_an.rename({"TXAB":"nombre"},axis=1)
df2_an["taux%"]=df2_an["mq"]*100/df2_an["nombre"]
df2_an=df2_an.sort_values(by=["taux%"],ascending=False)

In [30]:
df2_an

      an  mq  nombre      taux%
2   1998  75     503  14.910537
0   1996  38     496   7.661290
1   1997  40     540   7.407407
16  2012  25     671   3.725782
28  2024  21     678   3.097345
14  2010  20     667   2.998501
10  2006  19     637   2.982732
4   2000  13     505   2.574257
29  2025  17     679   2.503682
27  2023  17     681   2.496329
3   1999  12     494   2.429150
8   2004  14     579   2.417962
9   2005  13     553   2.350814
24  2020  14     653   2.143951
7   2003  12     592   2.027027
5   2001  10     514   1.945525
26  2022  13     684   1.900585
20  2016  13     685   1.897810
18  2014  13     687   1.892285
25  2021  12     684   1.754386
11  2007  10     671   1.490313
22  2018   9     689   1.306241
19  2015   9     689   1.306241
12  2008   6     678   0.884956
15  2011   6     684   0.877193
23  2019   5     679   0.736377
13  2009   4     683   0.585652
17  2013   4     693   0.577201
21  2017   1     693   0.144300
6   2002   0     555   0.000000

In [31]:
df2_mois=df2.groupby(by=["mois"],as_index=False).agg({"mq":"sum","TXAB":"count"})
df2_mois=df2_mois.rename({"TXAB":"nombre"},axis=1)
df2_mois["taux%"]=df2_mois["mq"]*100/df2_an["nombre"]
df2_mois=df2_mois.sort_values(by=["taux%"],ascending=False)

In [32]:
df2_mois

   mois  mq  nombre      taux%
0    01  51    1542  10.282258
9    10  51    1575   9.222423
5    06  45    1571   8.754864
1    02  47    1561   8.703704
2    03  42    1574   8.349901
3    04  38    1584   7.692308
6    07  38    1585   6.846847
8    09  34    1574   5.872193
7    08  34    1582   5.743243
4    05  28    1569   5.544554
11   12  34    1588   5.067064
10   11  23    1591   3.610675

In [40]:
#Lecture des stations au format geojson
##téléchargé à partie de https://www.data.gouv.fr/datasets/liste-des-stations-en-open-data-du-reseau-meteorologique-infoclimat-static-et-meteo-france-synop

import geopandas as gpd

In [41]:
info_stations=gpd.read_file("/home/dominique/DATA/meteo/stations_xhr.json")

In [42]:
info_stations

,id,name,elevation,license,country,departement,last_activity,geometry
0,07005,Abbeville,69,"{'code': 0, 'license': 'Etalab Open License', ...",FR,80,2026-02-02T09:00:00Z,POINT (1.834 50.136)
1,07015,Lille-Lesquin,47,"{'code': 0, 'license': 'Etalab Open License', ...",FR,59,2026-02-02T09:00:00Z,POINT (3.0975 50.57)
2,07020,Cap de La Hague,6,"{'code': 0, 'license': 'Etalab Open License', ...",FR,50,2026-02-02T09:00:00Z,POINT (-1.93983 49.72517)
3,07027,Caen-Carpiquet,67,"{'code': 0, 'license': 'Etalab Open License', ...",FR,14,2026-02-02T09:00:00Z,POINT (-0.45617 49.18)
4,07037,Rouen-Boos,156,"{'code': 0, 'license': 'Etalab Open License', ...",FR,76,2026-02-02T09:00:00Z,POINT (1.17833 49.3895)
...,...,...,...,...,...,...,...,...
1211,STATIC0455,Chartrettes,80,"{'code': 1, 'license': 'CC BY', 'url': 'https:...",FR,77,2026-02-02T09:20:00Z,POINT (2.70083 48.48808)
1212,STATIC0456,Échiré,37,"{'code': 2, 'license': 'NON-COMMERCIAL ONLY: C...",FR,79,2026-02-02T09:20:00Z,POINT (-0.4407 46.3873)
1213,STATIC0457,Chevenoz,830,"{'code': 2, 'license': 'NON-COMMERCIAL ONLY: C...",FR,74,2026-02-02T09:20:00Z,POINT (6.64816 46.3371)
1214,STATIC0458,Moret-Loing-et-Orvanne,56,"{'code': 1, 'license': 'CC BY', 'url': 'https:...",FR,77,2026-02-02T09:20:00Z,POINT (2.80943 48.3613)
1215,STATIC0459,Tauves - La Chaleille,1010,"{'code': 2, 'license': 'NON-COMMERCIAL ONLY: C...",FR,63,2026-02-02T09:20:00Z,POINT (2.66742 45.5702)

In [44]:
info_stations.explore()

In [48]:
#Croisement avec les id disponibles dans le fichier des températures

##Mise au format string et ajout d'un 0
df2["NUM_POSTE"]=df2["NUM_POSTE"].astype("str")
df2["NUM_POSTE"]=df2["NUM_POSTE"].apply(lambda x: "0"+x if len(x)==4 else x)

##liste
liste_id_stations=list(np.unique(df2["NUM_POSTE"]))

In [51]:
info_stations=info_stations[info_stations["id"].isin(liste_id_stations)]

In [52]:
info_stations

,id,name,elevation,license,country,departement,last_activity,geometry
0,07005,Abbeville,69,"{'code': 0, 'license': 'Etalab Open License', ...",FR,80,2026-02-02T09:00:00Z,POINT (1.834 50.136)
1,07015,Lille-Lesquin,47,"{'code': 0, 'license': 'Etalab Open License', ...",FR,59,2026-02-02T09:00:00Z,POINT (3.0975 50.57)
2,07020,Cap de La Hague,6,"{'code': 0, 'license': 'Etalab Open License', ...",FR,50,2026-02-02T09:00:00Z,POINT (-1.93983 49.72517)
3,07027,Caen-Carpiquet,67,"{'code': 0, 'license': 'Etalab Open License', ...",FR,14,2026-02-02T09:00:00Z,POINT (-0.45617 49.18)
4,07037,Rouen-Boos,156,"{'code': 0, 'license': 'Etalab Open License', ...",FR,76,2026-02-02T09:00:00Z,POINT (1.17833 49.3895)
6,07110,Brest-Guipavas,92,"{'code': 0, 'license': 'Etalab Open License', ...",FR,29,2026-02-02T09:00:00Z,POINT (-4.39117 48.45383)
7,07117,Ploumanac'h - Perros,55,"{'code': 0, 'license': 'Etalab Open License', ...",FR,22,2026-02-02T09:00:00Z,POINT (-3.47317 48.82583)
8,07130,Rennes-St Jacques,36,"{'code': 0, 'license': 'Etalab Open License', ...",FR,35,2026-02-02T09:00:00Z,POINT (-1.734 48.06883)
9,07139,Alençon - Valframbert,143,"{'code': 0, 'license': 'Etalab Open License', ...",FR,61,2026-02-02T09:00:00Z,POINT (0.11017 48.4455)
10,07149,Orly - Athis-Mons,86,"{'code': 0, 'license': 'Etalab Open License', ...",FR,91,2026-02-02T09:00:00Z,POINT (2.397 48.718)
11,07168,Troyes-Barberey,112,"{'code': 0, 'license': 'Etalab Open License', ...",FR,10,2026-02-02T09:00:00Z,POINT (4.02 48.32467)
12,07181,Nancy-Ochey,336,"{'code': 0, 'license': 'Etalab Open License', ...",FR,54,2026-02-02T09:00:00Z,POINT (5.95983 48.581)
13,07190,Strasbourg-Entzheim,150,"{'code': 0, 'license': 'Etalab Open License', ...",FR,67,2026-02-02T09:00:00Z,POINT (7.64033 48.5495)
14,07207,Belle Ile-Le Talut,34,"{'code': 0, 'license': 'Etalab Open License', ...",FR,56,2026-02-02T09:00:00Z,POINT (-3.21833 47.29433)
15,07222,Nantes-Atlantique,26,"{'code': 0, 'license': 'Etalab Open License', ...",FR,44,2026-02-02T09:00:00Z,POINT (-1.60883 47.15)
16,07240,Tours - Parcay-Meslay,108,"{'code': 0, 'license': 'Etalab Open License', ...",FR,37,2026-02-02T09:00:00Z,POINT (0.72733 47.4445)
17,07255,Bourges,161,"{'code': 0, 'license': 'Etalab Open License', ...",FR,18,2026-02-02T09:00:00Z,POINT (2.35983 47.05917)
18,07280,Dijon-Longvic,219,"{'code': 0, 'license': 'Etalab Open License', ...",FR,21,2026-02-02T09:00:00Z,POINT (5.08833 47.26783)
19,07299,Bâle-Mulhouse,263,"{'code': 0, 'license': 'Etalab Open License', ...",FR,68,2026-02-02T09:00:00Z,POINT (7.51 47.61433)
20,07314,Pointe de Chassiron,11,"{'code': 0, 'license': 'Etalab Open License', ...",FR,17,2026-02-02T09:00:00Z,POINT (-1.41167 46.04683)
21,07335,Poitiers-Biard,125,"{'code': 0, 'license': 'Etalab Open License', ...",FR,86,2026-02-02T09:00:00Z,POINT (0.31433 46.59383)
22,07434,Limoges-Bellegarde,402,"{'code': 0, 'license': 'Etalab Open License', ...",FR,87,2026-02-02T09:00:00Z,POINT (1.175 45.86117)
23,07460,Clermont-Ferrand - Aulnat,331,"{'code': 0, 'license': 'Etalab Open License', ...",FR,63,2026-02-02T09:00:00Z,POINT (3.14933 45.78683)
24,07471,Le Puy-Loudes,833,"{'code': 0, 'license': 'Etalab Open License', ...",FR,43,2026-02-02T09:00:00Z,POINT (3.764 45.0745)
25,07481,Lyon-St Exupéry,235,"{'code': 0, 'license': 'Etalab Open License', ...",FR,69,2026-02-02T09:00:00Z,POINT (5.07783 45.7265)
26,07510,Bordeaux-Mérignac,47,"{'code': 0, 'license': 'Etalab Open License', ...",FR,33,2026-02-02T09:00:00Z,POINT (-0.69133 44.83067)
27,07535,Gourdon,260,"{'code': 0, 'license': 'Etalab Open License', ...",FR,46,2026-02-02T09:00:00Z,POINT (1.39667 44.745)
29,07577,Montélimar - Ancone,73,"{'code': 0, 'license': 'Etalab Open License', ...",FR,26,2026-02-02T09:00:00Z,POINT (4.733 44.58117)
30,07591,Embrun,873,"{'code': 0, 'license': 'Etalab Open License', ...",FR,5,2026-02-02T09:00:00Z,POINT (6.50867 44.57117)
31,07607,Mont-de-Marsan,59,"{'code': 0, 'license': 'Etalab Open License', ...",FR,40,2026-02-02T09:00:00Z,POINT (-0.50017 43.90983)
32,07621,Tarbes - Ossun - Lourdes,360,"{'code': 0, 'license': 'Etalab Open License', ...",FR,65,2026-02-02T09:00:00Z,POINT (0 43.188)
33,07627,Saint-Girons - Antichan,414,"{'code': 0, 'license': 'Etalab Open License', ...",FR,9,2026-02-02T09:00:00Z,POINT (1.10683 43.00533)
34,07630,Toulouse-Blagnac,151,"{'code': 0, 'license': 'Etalab Open License', ...",FR,31,2026-02-02T09:00:00Z,POINT (1.37883 43.621)
35,07643,Montpellier - Fréjorgues,1,"{'code': 0, 'license': 'Etalab Open License', ...",FR,34,2026-02-02T09:00:00Z,POINT (3.96467 43.57617)
36,07650,Marseille-Marignane (Marseille Provence),9,"{'code': 0, 'license': 'Etalab Open License', ...",FR,13,2026-02-02T09:00:00Z,POINT (5.216 43.43767)
37,07661,Saint-Mandrier-sur-Mer - Cap Cépet,115,"{'code': 0, 'license': 'Etalab Open License', ...",FR,83,2025-01-13T11:00:00Z,POINT (5.94083 43.07933)
38,07690,Nice - Côte d'Azur,2,"{'code': 0, 'license': 'Etalab Open License', ...",FR,6,2026-02-02T09:00:00Z,POINT (7.209 43.64883)
39,07747,Perpignan - Rivesaltes,42,"{'code': 0, 'license': 'Etalab Open License', ...",FR,66,2026-02-02T09:00:00Z,POINT (2.87283 42.73717)
40,07761,Ajaccio - Campo dell'Oro,5,"{'code': 0, 'license': 'Etalab Open License', ...",FR,20,2026-02-02T09:00:00Z,POINT (8.79267 41.918)
41,07790,Bastia - Poretta,10,"{'code': 0, 'license': 'Etalab Open License', ...",FR,20,2026-02-02T09:00:00Z,POINT (9.48517 42.54067)

In [53]:
info_stations.explore()

In [54]:
#Préparation d'un fichier mensuel par station et année + ajou du nom de la station
##regroupement
df2_annuel=df2.groupby(by=["an","NUM_POSTE"] , as_index=False).agg({"NBJTX30":"sum"})

##réduction du df des infos stations (on laisse tomber les coordonnées pour l'instant)
df_info_stations=info_stations[["id","name"]]

##fusion
df2_annuel=df2_annuel.merge(right=df_info_stations,left_on="NUM_POSTE",right_on="id",how="left")

In [56]:
#Nettoyage
df2_annuel=df2_annuel.dropna()
df2_annuel=df2_annuel.drop(["NUM_POSTE"],axis=1)

#Renommage des colonnes
df2_annuel=df2_annuel.rename({"an":"Année","id":"ID_station","name":"Station","NBJTX30":"Jours>=30°C"},axis=1)

#Réarrangement des colonnes
df2_annuel=df2_annuel.reindex(["Année","ID_station","Jours>=30°C","Station"],axis=1)

In [57]:
df2_annuel

     Année ID_station  Jours>=30°C                             Station
0     1996      07005          1.0                           Abbeville
1     1996      07015          2.0                       Lille-Lesquin
2     1996      07020          0.0                     Cap de La Hague
3     1996      07027          4.0                      Caen-Carpiquet
4     1996      07037          4.0                          Rouen-Boos
...    ...        ...          ...                                 ...
1627  2025      07661          0.0  Saint-Mandrier-sur-Mer - Cap Cépet
1628  2025      07690         22.0                  Nice - Côte d'Azur
1629  2025      07747         60.0              Perpignan - Rivesaltes
1630  2025      07761         52.0            Ajaccio - Campo dell'Oro
1631  2025      07790         48.0                    Bastia - Poretta

[1187 rows x 4 columns]

In [61]:
#Nombre final de stations
nb_stations=len(list(np.unique(df2_annuel["ID_station"])))

In [62]:
print(f"Le nombre de stations rettenues pour les statistiques est {nb_stations}")

Le nombre de stations rettenues pour les statistiques est 40

In [60]:
#export
df2_annuel.to_csv("/home/dominique/DATA/meteo/meteo_climat_omm_annuel.csv",index=False)